export interface EmojiShortcodePreset {
  value: string;
  aliases: readonly string[];
}

export const COMMON_EMOJI_SHORTCODES: Record<string, string> = {
  '+1': '👍',
  '-1': '👎',
  '100': '💯',
  '1234': '🔢',
  airplane: '✈️',
  alarm_clock: '⏰',
  anchor: '⚓',
  angry: '😠',
  anguished: '😧',
  astonished: '😲',
  ballot_box_with_check: '☑️',
  bangbang: '‼️',
  bank: '🏦',
  bar_chart: '📊',
  beer: '🍺',
  beers: '🍻',
  bell: '🔔',
  bento: '🍱',
  black_heart: '🖤',
  blush: '😊',
  blue_heart: '💙',
  boom: '💥',
  broken_heart: '💔',
  brown_heart: '🤎',
  bulb: '💡',
  bullettrain_front: '🚅',
  bus: '🚌',
  cake: '🍰',
  calendar: '📅',
  call_me_hand: '🤙',
  camera: '📷',
  car: '🚗',
  chart_with_upwards_trend: '📈',
  check: '✅',
  cherry_blossom: '🌸',
  clap: '👏',
  clipboard: '📋',
  clock: '🕒',
  cloud: '☁️',
  coffee: '☕',
  cold_sweat: '😰',
  collision: '💥',
  computer: '💻',
  confounded: '😖',
  confused: '😕',
  convenience_store: '🏪',
  compass: '🧭',
  credit_card: '💳',
  crossed_fingers: '🤞',
  crown: '👑',
  cry: '😢',
  cupid: '💘',
  date: '📅',
  disappointed: '😞',
  disappointed_relieved: '😥',
  dizzy: '💫',
  dizzy_face: '😵',
  dollar: '💵',
  drooling_face: '🤤',
  earth_asia: '🌏',
  email: '✉️',
  envelope: '✉️',
  exclamation: '❗',
  expressionless: '😑',
  eye: '👁️',
  eyes: '👀',
  face_with_head_bandage: '🤕',
  face_with_symbols_on_mouth: '🤬',
  face_with_thermometer: '🤒',
  fearful: '😨',
  fire: '🔥',
  flight: '✈️',
  flushed: '😳',
  four_leaf_clover: '🍀',
  frowning: '😦',
  frowning_face: '☹️',
  gem: '💎',
  gift: '🎁',
  gift_heart: '💝',
  globe_with_meridians: '🌐',
  green_heart: '💚',
  grey_exclamation: '❕',
  grey_question: '❔',
  grimacing: '😬',
  grin: '😁',
  grinning: '😀',
  hand: '✋',
  handshake: '🤝',
  hankey: '💩',
  heart: '❤️',
  heartbeat: '💓',
  heart_decoration: '💟',
  heart_eyes: '😍',
  heartpulse: '💗',
  heavy_check_mark: '✔️',
  heavy_heart_exclamation: '❣️',
  hotel: '🏨',
  house: '🏠',
  hospital: '🏥',
  hushed: '😯',
  information_source: 'ℹ️',
  innocent: '😇',
  interrobang: '⁉️',
  iphone: '📱',
  japan: '🗾',
  jp: '🇯🇵',
  joy: '😂',
  kissing: '😗',
  kissing_closed_eyes: '😚',
  kissing_heart: '😘',
  laughing: '😆',
  lying_face: '🤥',
  love_you_gesture: '🤟',
  map: '🗺️',
  mask: '😷',
  medal: '🏅',
  memo: '📝',
  metal: '🤘',
  money_mouth_face: '🤑',
  moneybag: '💰',
  muscle: '💪',
  nauseated_face: '🤢',
  negative_squared_cross_mark: '❎',
  nerd_face: '🤓',
  neutral_face: '😐',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  no_mouth: '😶',
  office: '🏢',
  ok_hand: '👌',
  open_mouth: '😮',
  orange_heart: '🧡',
  paperclip: '📎',
  parking: '🅿️',
  partying_face: '🥳',
  peace_symbol: '☮️',
  pencil: '📝',
  pensive: '😔',
  persevere: '😣',
  phone: '☎️',
  plane: '✈️',
  pleading_face: '🥺',
  point_down: '👇',
  point_left: '👈',
  point_right: '👉',
  point_up: '☝️',
  point_up_2: '👆',
  poop: '💩',
  pray: '🙏',
  prohibited: '🚫',
  purple_heart: '💜',
  pushpin: '📌',
  question: '❓',
  rage: '😡',
  raised_hand: '✋',
  raised_hands: '🙌',
  ramen: '🍜',
  red_heart: '❤️',
  recycle: '♻️',
  relaxed: '☺️',
  relieved: '😌',
  revolving_hearts: '💞',
  rofl: '🤣',
  rocket: '🚀',
  roll_eyes: '🙄',
  round_pushpin: '📍',
  satisfied: '😆',
  scream: '😱',
  school: '🏫',
  shushing_face: '🤫',
  ship: '🚢',
  skin_tone_2: '🏻',
  skin_tone_3: '🏼',
  skin_tone_4: '🏽',
  skin_tone_5: '🏾',
  skin_tone_6: '🏿',
  sleeping: '😴',
  sleepy: '😪',
  slightly_frowning_face: '🙁',
  slightly_smiling_face: '🙂',
  smile: '😄',
  smiley: '😃',
  smiling_face_with_3_hearts: '🥰',
  smiling_imp: '😈',
  smirk: '😏',
  sneezing_face: '🤧',
  sob: '😭',
  snowflake: '❄️',
  sparkles: '✨',
  stars: '🌠',
  sparkling_heart: '💖',
  speech_balloon: '💬',
  star: '⭐',
  star2: '🌟',
  star_struck: '🤩',
  stuck_out_tongue: '😛',
  stuck_out_tongue_closed_eyes: '😝',
  stuck_out_tongue_winking_eye: '😜',
  sun: '☀️',
  sunny: '☀️',
  sunglasses: '😎',
  sushi: '🍣',
  sweat: '😓',
  sweat_smile: '😅',
  tada: '🎉',
  taxi: '🚕',
  tea: '🍵',
  thinking_face: '🤔',
  thought_balloon: '💭',
  thumbsdown: '👎',
  thumbsup: '👍',
  ticket: '🎫',
  tired_face: '😫',
  train: '🚃',
  train2: '🚆',
  triumph: '😤',
  trophy: '🏆',
  unamused: '😒',
  upside_down_face: '🙃',
  umbrella: '☂️',
  v: '✌️',
  vomiting_face: '🤮',
  warning: '⚠️',
  wave: '👋',
  weary: '😩',
  wheelchair: '♿',
  wheelchair_symbol: '♿',
  white_check_mark: '✅',
  white_heart: '🤍',
  wink: '😉',
  worried: '😟',
  world_map: '🗺️',
  x: '❌',
  yawning_face: '🥱',
  yellow_heart: '💛',
  yen: '💴',
  yum: '😋',
  zipper_mouth_face: '🤐',
  zap: '⚡',
};

function normalizeEmojiAlias(alias: string): string {
  return alias
    .trim()
    .replace(/^:+|:+$/g, '')
    .replace(/-/g, '_')
    .toLowerCase();
}

export function replaceEmojiShortcodes(
  value: string,
  customPresets: readonly EmojiShortcodePreset[] = [],
): string {
  if (!value.includes(':')) return value;

  const aliasMap = new Map(Object.entries(COMMON_EMOJI_SHORTCODES));
  for (const preset of customPresets) {
    if (!preset.value) continue;
    for (const alias of preset.aliases) {
      const normalizedAlias = normalizeEmojiAlias(alias);
      if (normalizedAlias) aliasMap.set(normalizedAlias, preset.value);
    }
  }

  return value.replace(/:([A-Za-z0-9_+\-]+):/g, (match, alias: string) => {
    return aliasMap.get(normalizeEmojiAlias(alias)) ?? match;
  });
}
